@startuml
title "Fpass Content Display"

autonumber
skinparam MaxMessageSize 100

!$cacheTime = "~15min"

actor User

box Partner
participant PartnerApp as "App"
participant PartnerAPI as "API"
end box

box Fpass
participant API
participant WebApp
end box

group Display
User -> PartnerApp: Access Home

group Featured
PartnerApp -> PartnerAPI: Invoke
PartnerAPI -> API: **GET /display/featured**
API -> PartnerAPI: Response
PartnerAPI -> PartnerApp: Response
PartnerApp -> PartnerApp: Persist Cache (for $cacheTime)
PartnerApp -> User: Display Featured
end

group Sections
PartnerApp -> PartnerAPI: Invoke
PartnerAPI -> API: **GET /display/sections**
API -> PartnerAPI: Response
loop For each section
PartnerAPI -> API: **GET /display/sections/{sectionId}/resources**
API -> PartnerAPI: Response
end
PartnerAPI -> PartnerApp: Response
PartnerApp -> PartnerApp: Persist Cache (for $cacheTime)
PartnerApp -> User: Display Sections with Resources
end

group Resume Lessons
PartnerApp -> PartnerAPI: Invoke
PartnerAPI -> API: **GET /display/resume/lessons**
API -> PartnerAPI: Response
PartnerAPI -> PartnerApp: Response
PartnerApp -> PartnerApp: Persist Cache (for $cacheTime)
PartnerApp -> User: Display Resume Lessons
end

group Cache (next $cacheTime)
User -> PartnerApp: Reload Page
PartnerApp -> PartnerApp: Retrive from Cache
PartnerApp -> User: Display
end

end
' Display

@enduml