@startuml
title "FPass Certificate Flow"

autonumber
skinparam MaxMessageSize 100

actor User

box FPass
participant WebApp
participant ContentProviderAPI
end box

box CertificatePartner
participant CertificateProvider
end box

group Certificate
User -> WebApp: Acessa
User -> WebApp: Aciona geração de certificado
group Create
WebApp -> ContentProviderAPI: **POST /certificate/passport**
ContentProviderAPI -> CertificateProvider: Aciona
return
ContentProviderAPI -> ContentProviderAPI: Persiste
ContentProviderAPI -> WebApp: Retorna dados
note right
**Response**
{
  "createdAt": "2021-10-11T04:09:46.520Z",
  "updatedAt": "2021-10-11T04:09:46.520Z",
  "resourceType": "certificate",
  "resourceId": "2da4032b-1734-463a-af90-e6311ca13702",
  "imageUrl": "https://site.com/image.png"
}
end note
end
group Retrive
WebApp -> ContentProviderAPI: **GET /certificate/passport**
ContentProviderAPI -> WebApp: Retorna dados
note right
**Response**
end note
end
end
@enduml