@startuml
title "Fpass Content User"

autonumber
skinparam MaxMessageSize 100

!$cacheTime = "~15min"

actor User

box Partner
participant PartnerApp as "App"
participant PartnerAPI as "API"
end box

box Fpass
participant API
participant WebApp
end box

group User

group New
User -> PartnerApp: Email and password
PartnerApp -> PartnerAPI: Invoke
PartnerAPI -> API: **POST /users**
note left
{
  ...,
  data: {
    externalId: "partnersUserId"
  }
}
end note
API -> PartnerAPI: Response
PartnerAPI -> PartnerApp: Response

group 2 Factor Activate
API -> User: Activation Notification
User -> WebApp: Activate with token
end

end
' New

group Credential
User -> PartnerApp: Email and password
PartnerApp -> PartnerAPI: Invoke
PartnerAPI -> API: **POST /users/credential**
API -> PartnerAPI: Response
PartnerAPI -> PartnerApp: Response
PartnerApp -> PartnerApp: Persist JWT
end

group Recover
User -> PartnerApp: Email
PartnerApp -> PartnerAPI: Invoke
PartnerAPI -> API: **POST /users/recover**
API -> PartnerAPI: Response
PartnerAPI -> PartnerApp: Response

group 2 Factor Recover
API -> User: Recover Notification
User -> WebApp: Recover with token
end

end
' Recover
end
' User

@enduml