/* tslint:disable */
/* eslint-disable */
/**
 * @holding-fpass/content-provider-api
 * Content Provider API
 *
 * OpenAPI spec version: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CreateInteractionDto } from '../models';
import { OmitTypeClass } from '../models';
/**
 * DataAnalyticsApi - axios parameter creator
 * @export
 */
export const DataAnalyticsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateInteractionDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createInteraction: async (body: CreateInteractionDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createInteraction.');
            }
            const localVarPath = `/interaction`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DataAnalyticsApi - functional programming interface
 * @export
 */
export const DataAnalyticsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateInteractionDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createInteraction(body: CreateInteractionDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OmitTypeClass>> {
            const localVarAxiosArgs = await DataAnalyticsApiAxiosParamCreator(configuration).createInteraction(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DataAnalyticsApi - factory interface
 * @export
 */
export const DataAnalyticsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {CreateInteractionDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createInteraction(body: CreateInteractionDto, options?: any): AxiosPromise<OmitTypeClass> {
            return DataAnalyticsApiFp(configuration).createInteraction(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DataAnalyticsApi - object-oriented interface
 * @export
 * @class DataAnalyticsApi
 * @extends {BaseAPI}
 */
export class DataAnalyticsApi extends BaseAPI {
    /**
     * 
     * @param {CreateInteractionDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataAnalyticsApi
     */
    public createInteraction(body: CreateInteractionDto, options?: any) {
        return DataAnalyticsApiFp(this.configuration).createInteraction(body, options).then((request) => request(this.axios, this.basePath));
    }
}
