/* tslint:disable */
/* eslint-disable */
/**
 * Fpass Content API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CertificateType } from '../models';
import { Resource } from '../models';
/**
 * CertificateApi - axios parameter creator
 * @export
 */
export const CertificateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Gerar um certificado
         * @param {CertificateType} type Tipo de certificado a ser obtido
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCertificate: async (type: CertificateType, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            if (type === null || type === undefined) {
                throw new RequiredError('type','Required parameter type was null or undefined when calling createCertificate.');
            }
            const localVarPath = `/certificate/{type}`
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Obter um certificado
         * @param {CertificateType} type Tipo de certificado a ser obtido
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCertificate: async (type: CertificateType, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            if (type === null || type === undefined) {
                throw new RequiredError('type','Required parameter type was null or undefined when calling getCertificate.');
            }
            const localVarPath = `/certificate/{type}`
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CertificateApi - functional programming interface
 * @export
 */
export const CertificateApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Gerar um certificado
         * @param {CertificateType} type Tipo de certificado a ser obtido
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCertificate(type: CertificateType, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Resource>> {
            const localVarAxiosArgs = await CertificateApiAxiosParamCreator(configuration).createCertificate(type, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Obter um certificado
         * @param {CertificateType} type Tipo de certificado a ser obtido
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCertificate(type: CertificateType, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Resource>> {
            const localVarAxiosArgs = await CertificateApiAxiosParamCreator(configuration).getCertificate(type, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * CertificateApi - factory interface
 * @export
 */
export const CertificateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Gerar um certificado
         * @param {CertificateType} type Tipo de certificado a ser obtido
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCertificate(type: CertificateType, options?: any): AxiosPromise<Resource> {
            return CertificateApiFp(configuration).createCertificate(type, options).then((request) => request(axios, basePath));
        },
        /**
         * Obter um certificado
         * @param {CertificateType} type Tipo de certificado a ser obtido
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCertificate(type: CertificateType, options?: any): AxiosPromise<Resource> {
            return CertificateApiFp(configuration).getCertificate(type, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CertificateApi - object-oriented interface
 * @export
 * @class CertificateApi
 * @extends {BaseAPI}
 */
export class CertificateApi extends BaseAPI {
    /**
     * Gerar um certificado
     * @param {CertificateType} type Tipo de certificado a ser obtido
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CertificateApi
     */
    public createCertificate(type: CertificateType, options?: any) {
        return CertificateApiFp(this.configuration).createCertificate(type, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Obter um certificado
     * @param {CertificateType} type Tipo de certificado a ser obtido
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CertificateApi
     */
    public getCertificate(type: CertificateType, options?: any) {
        return CertificateApiFp(this.configuration).getCertificate(type, options).then((request) => request(this.axios, this.basePath));
    }
}
