/* tslint:disable */
/* eslint-disable */
/**
 * Fpass Content API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Resource } from '../models';
import { Uuid } from '../models';
/**
 * DisplayApi - axios parameter creator
 * @export
 */
export const DisplayApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Banners em destaque de cursos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDisplayFeatured: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/display/featured`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retormar a aula
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDisplayResumeLesson: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/display/resume/lessons`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Lista de seções de recursos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDisplaySections: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/display/sections`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Lista de seções de recursos
         * @param {Uuid} id resourceId de um resource com type display.section
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDisplaySectionsResources: async (id: Uuid, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getDisplaySectionsResources.');
            }
            const localVarPath = `/display/sections/{id}/resources`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DisplayApi - functional programming interface
 * @export
 */
export const DisplayApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Banners em destaque de cursos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDisplayFeatured(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Resource>> {
            const localVarAxiosArgs = await DisplayApiAxiosParamCreator(configuration).getDisplayFeatured(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retormar a aula
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDisplayResumeLesson(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Resource>> {
            const localVarAxiosArgs = await DisplayApiAxiosParamCreator(configuration).getDisplayResumeLesson(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Lista de seções de recursos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDisplaySections(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Resource>> {
            const localVarAxiosArgs = await DisplayApiAxiosParamCreator(configuration).getDisplaySections(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Lista de seções de recursos
         * @param {Uuid} id resourceId de um resource com type display.section
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDisplaySectionsResources(id: Uuid, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Resource>> {
            const localVarAxiosArgs = await DisplayApiAxiosParamCreator(configuration).getDisplaySectionsResources(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DisplayApi - factory interface
 * @export
 */
export const DisplayApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Banners em destaque de cursos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDisplayFeatured(options?: any): AxiosPromise<Resource> {
            return DisplayApiFp(configuration).getDisplayFeatured(options).then((request) => request(axios, basePath));
        },
        /**
         * Retormar a aula
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDisplayResumeLesson(options?: any): AxiosPromise<Resource> {
            return DisplayApiFp(configuration).getDisplayResumeLesson(options).then((request) => request(axios, basePath));
        },
        /**
         * Lista de seções de recursos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDisplaySections(options?: any): AxiosPromise<Resource> {
            return DisplayApiFp(configuration).getDisplaySections(options).then((request) => request(axios, basePath));
        },
        /**
         * Lista de seções de recursos
         * @param {Uuid} id resourceId de um resource com type display.section
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDisplaySectionsResources(id: Uuid, options?: any): AxiosPromise<Resource> {
            return DisplayApiFp(configuration).getDisplaySectionsResources(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DisplayApi - object-oriented interface
 * @export
 * @class DisplayApi
 * @extends {BaseAPI}
 */
export class DisplayApi extends BaseAPI {
    /**
     * Banners em destaque de cursos
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisplayApi
     */
    public getDisplayFeatured(options?: any) {
        return DisplayApiFp(this.configuration).getDisplayFeatured(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retormar a aula
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisplayApi
     */
    public getDisplayResumeLesson(options?: any) {
        return DisplayApiFp(this.configuration).getDisplayResumeLesson(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Lista de seções de recursos
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisplayApi
     */
    public getDisplaySections(options?: any) {
        return DisplayApiFp(this.configuration).getDisplaySections(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Lista de seções de recursos
     * @param {Uuid} id resourceId de um resource com type display.section
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisplayApi
     */
    public getDisplaySectionsResources(id: Uuid, options?: any) {
        return DisplayApiFp(this.configuration).getDisplaySectionsResources(id, options).then((request) => request(this.axios, this.basePath));
    }
}
