/* tslint:disable */
/* eslint-disable */
/**
 * @holding-fpass/content-provider-api
 * Content Provider API
 *
 * OpenAPI spec version: 0.2.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateMfaEvent
 */
export interface CreateMfaEvent {
    /**
     * 
     * @type {string}
     * @memberof CreateMfaEvent
     */
    eventId: any;
    /**
     * 
     * @type {string}
     * @memberof CreateMfaEvent
     */
    eventType: any;
    /**
     * 
     * @type {string}
     * @memberof CreateMfaEvent
     */
    eventDate: any;
    /**
     * 
     * @type {string}
     * @memberof CreateMfaEvent
     */
    resourceId: any;
    /**
     * 
     * @type {string}
     * @memberof CreateMfaEvent
     */
    resourceType: any;
}
