/* tslint:disable */
/* eslint-disable */
/**
 * @holding-fpass/content-provider-api
 * Content Provider API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateMfaDto
 */
export interface CreateMfaDto {
    /**
     * Identificação do browser
     * @type {string}
     * @memberof CreateMfaDto
     */
    machineId: any;
    /**
     * 
     * @type {string}
     * @memberof CreateMfaDto
     */
    type: CreateMfaDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateMfaDto
     */
    value: any;
    /**
     * 
     * @type {MfaExtra}
     * @memberof CreateMfaDto
     */
    extra: any;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateMfaDtoTypeEnum {
    Email = 'email'
}

