/* tslint:disable */
/* eslint-disable */
/**
 * @holding-fpass/content-provider-api
 * Content Provider API
 *
 * OpenAPI spec version: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MfaExtra
 */
export interface MfaExtra {
    /**
     * 
     * @type {string}
     * @memberof MfaExtra
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof MfaExtra
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof MfaExtra
     */
    phone?: any;
}
