/* tslint:disable */
/* eslint-disable */
/**
 * @holding-fpass/content-provider-api
 * Content Provider API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/certificate-api';
export * from './apis/mfaapi';
export * from './apis/status-api';

