/* tslint:disable */
/* eslint-disable */
/**
 * Fpass Content API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NewUserRequest
 */
export interface NewUserRequest {
    /**
     * 
     * @type {string}
     * @memberof NewUserRequest
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof NewUserRequest
     */
    email?: any;
    /**
     * 
     * @type {Password}
     * @memberof NewUserRequest
     */
    password?: any;
    /**
     * 
     * @type {NewUserRequestData}
     * @memberof NewUserRequest
     */
    data?: any;
}
